name = "Zarr"
uuid = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
version = "0.11.0"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ZarrBlosc = "5717d1f5-dd42-40cd-8e77-00dfad1079f5"
ZarrCore = "77f5b75c-4c08-499f-ba13-550b0a0af171"
ZarrGCS = "b0c5ce8f-018f-417d-9deb-9816b6363039"
ZarrHTTP = "904a97b2-8abf-4ac8-b211-6540db5c2c8c"
ZarrS3 = "3ac672aa-0e94-41ce-be0d-2f83c20261dd"
ZarrZip = "54bcf1c8-e61d-4e4f-b375-463581846cca"
ZarrZlib = "5ee7c756-6ac8-46ad-a53f-994846513443"
ZarrZstd = "1a1ab68b-db27-4b87-8dee-6752e2bcfa1e"

[sources]
ZarrBlosc = {path = "../ZarrBlosc"}
ZarrCore = {path = "../ZarrCore"}
ZarrGCS = {path = "../ZarrGCS"}
ZarrHTTP = {path = "../ZarrHTTP"}
ZarrS3 = {path = "../ZarrS3"}
ZarrZip = {path = "../ZarrZip"}
ZarrZlib = {path = "../ZarrZlib"}
ZarrZstd = {path = "../ZarrZstd"}

[compat]
Preferences = "1.5.2"
ZarrBlosc = "0.11.0"
ZarrCore = "0.11.0"
ZarrGCS = "0.11.0"
ZarrHTTP = "0.11.0"
ZarrS3 = "0.11.0"
ZarrZip = "0.11.0"
ZarrZlib = "0.11.0"
ZarrZstd = "0.11.0"
julia = "1.10"
