[workspace]
projects = [
    "Zarr",
    "ZarrCore",
    "ZarrZip",
    "ZarrBlosc",
    "ZarrZlib",
    "ZarrZstd",
    "ZarrHTTP",
    "ZarrGCS",
    "ZarrS3",
    "ZarrTrimmable",
    "Zarr/test",
    "docs",
]
